export {default as author} from './author.js'
export {default as category} from './category.js'
export {default as navMenu} from './navMenu.js'
export {default as page} from './page.js'
export {default as person} from './person.js'
export {default as post} from './post.js'
export {default as route} from './route.js'
export {default as singletonAbout} from './singletonAbout.js'
export {default as siteSettings} from './siteSettings.js'
// export {default as team} from './team.js'
// export {default as teamsPage} from './teamsPage.js'